setupTasks:
  - task: git-clone
    inputs:
      repositoryUrl: 'https://github.com/jmatthiesen/personal-config'
      directory: 'c:\src'

  - task: powershell
    inputs:
      runAsUser: true #need a way to run PS scripts as a user
      workingDirectory: 'c:\src\personal-config'
      command: "Set-ItemProperty -Path HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes -Name InstallTheme -Value C:\Windows\resources\Themes\dark.theme -Force"
