setupTasks:
  - task: git-clone
    inputs:
      repositoryUrl: 'https://github.com/jmatthiesen/personal-config'
      directory: 'c:\src'

  - task: winget
    inputs:
      package: Balsamiq.Wireframes

# Setup tasks that must run "as user"
  - task: winget
    inputs:
      runAsUser: true
      package: 'Microsoft.PowerToys'

  - task: powershell
    inputs:
      runAsUser: true
      command: 'powershell -File c:\src\personal-config\setupenv.ps1'