# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  assertions:
    - resource: Microsoft.Windows.Developer/OsVersion
      directives:
        description: Verify min OS version requirement
        allowPrerelease: true
      settings:
        MinVersion: '10.0.22000'
  resources:
    - resource: Microsoft.Windows.Developer/DeveloperMode
      directives:
        description: Enable Developer Mode
        allowPrerelease: true
      settings:
        Ensure: Present
    - resource: Microsoft.Windows.Developer/EnableDarkMode
      directives:
        description: Enable Dark Mode
        allowPrerelease: true
      settings:
        Ensure: Present
    - resource: Microsoft.Windows.Developer/HideFileExtensions
      directives:
        description: Hide known file extensions
        allowPrerelease: true
      settings:
        Ensure: Absent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install PowerToys
        allowPrerelease: true
      settings:
        id: Microsoft.PowerToys
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Balsamiq Mockups
        allowPrerelease: true
      settings:
        id: Balsamiq.Wireframes
    - resource: PSDscResources/Script
      id: myVSSettings
      directives:
        description: Configure VS personal settings
        allowPrerelease: true
      settings:
        GetScript: |
          # Your custom PowerShell code to check app configuration
        TestScript: |
          return $false
        SetScript: |
          [System.Environment]::SetEnvironmentVariable("VS_UNIFIED_SETTINGS_PROFILE","${WinGetConfigRoot}\..\visual-studio-settings\", "User")

  configurationVersion: 0.2.0